language: python

os:
  - linux
  - osx
env:
  - TRAVIS_PYTHON_VERSION="2.7"
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - env: TRAVIS_PYTHON_VERSION="3.5"

sudo: required
dist: trusty

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
      - python-dev
      - libgdal1-dev
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran

services:
  - postgresql

python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - sudo apt-get -qq update


install:
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget -O miniconda.sh http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-MacOSX-x86_64.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda python
  # create environment in conda
  - conda create --yes --name gaia python=$TRAVIS_PYTHON_VERSION
  - source activate gaia
  - conda config --add channels conda-forge
  # install main packages
  - conda install -f --yes lapack gdal=1.10 numpy=1.10.4 six=1.9.0 requests=2.7.0 geopandas=0.1.1 pillow=3.1.1 celery=3.1.20 psycopg2=2.6.1 geoalchemy2=0.2.6
  # install test packages
  - pip install -r requirements-dev.txt
  - pip install -e .
  - source deactivate
  - source activate gaia
  

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_ci_test

script:
  - python -m unittest discover
  - flake8 --config tests/flake8.cfg gaia tests
